### ISSUE TITLE
[FEAT] Allow me to label the dice on the library so I can identify them thanks 😄 

### ISSUE THREAD

**Issue by Xander1599** [Carrera-Dev-Consulting/zombie_nomnom#24]
**Is your feature request related to a problem? Please describe.**
No its not really a problem, just would like to be able to identify a bad dice or a good dice or any dice...

**Describe the solution you'd like**
Add a label to each individual dice so I can label them it could also be undefined, I dont care either way. Just something so I know what dice it is.

**Describe alternatives you've considered**
Honestly theres no alternatives, would just be nice to uniquely identify a dice personally.

**Additional context**
N/A

**Comment by gxldCptRick** [comment]
Boo who needs labels 👎

**Comment by gxldCptRick** [comment]
Added tag FEAT to the title to make sure I can distinguish it faster
